flowchart TD
    A[System Team] -->| drawing with Mermaid | B
    B[Look for solutions]
    B -->| goal | E[output an svg file]
    B -->| interact with | D[codebased mermaid files ]
    B -->| develop | F[must works for forks]
    B -->| handling | G[creates pull-requests]
