#########################################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#########################################################################################

name: 'Generate svg.file from source'

on:
  push:
    branches:
      - main
    # Trigger was set only for mermaid related files
    paths:
      - '**/*.mermaid'
      - '**/*.mmd'
  # Testing reason
  workflow_dispatch:
jobs:
  generate-mermaid-files:
    runs-on: ubuntu-latest

    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
         node-version: 16
      - name: install mermaid cli
        run: |
          npm install -g @mermaid-js/mermaid-cli
      # verification if install of Mermaid CLI was successful
      #- name: print mmdc version
      #  run: |
      #    mmdc -V
      - name: checkout source repo
        uses: actions/checkout@v3.5.3
      - name: search for files
        id: search_files
        run: |
         echo "mermaid_files=$(find . -type f \( -name "*.mmd" -o -name "*.mermaid" \) | xargs )" >> $GITHUB_OUTPUT
      - name: show the found files
        run: echo "These files ${{ steps.search_files.outputs.mermaid_files }} are the maintained Mermaid files"
      - name: generate svg file
        id: generate
        run: |
          for file in ${{ steps.search_files.outputs.mermaid_files }};
            do
             mmdc -i $file -o ${file%.*}.svg
             echo "${file%.*}.svg"
             git add ${file%.*}.svg
            done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          commit-message: "chore(docs): update svg-files"
          branch: mermaid-updates
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: 'chore(docs): store repository Mermaid Diagramms in .svg files'
          body: |
            ### Description
            This Pull-Request was opened by an update on some Mermaid Files with this repository suffix `.mmd` or `.mermaid`.
          
            ### Checks
          
            Please ensure that the current showcased Mermaid File looks like you desired output.

            :information_source: We got updates on our Mermaid Files
             - please view the changes in the preview of this pull request
                         
             <!-- -->
          labels: |
            documentation
          assignees: FaGru3n
          reviewers: FaGru3n
