name: generate static PlantUML files
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate PlantUML Diagrams
        uses: rotaract/plantuml-action@v1.3.0
        with:
          format: svg
          pattern: "**.puml"
          
      - name: push static file to pr-branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          commit_message: 'chore(docs): add static puml *.svg files"'
          # Optional commit user and author settings
          commit_user_name: GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
