name: 'generate static Mermaid files'
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
         node-version: 16
      - name: install mermaid cli
        run: |
          npm install -g @mermaid-js/mermaid-cli
      - name: print mmdc version
        run: |
          mmdc -V
      - name: checkout source repo
        uses: actions/checkout@v3.5.3
      - name: search for files
        id: search_files
        run: |
         pwd
         echo "mermaid_files=$(find . -type f \( -name "*.mmd" -o -name "*.mermaid" \) | xargs )" >> $GITHUB_OUTPUT
      - name: show step output
        run: echo "step files from ${{ steps.search_files.outputs.mermaid_files }}"
      - name: generate svg file
        id: generated
        run: |
          for file in ${{ steps.search_files.outputs.mermaid_files }};
            do
             mmdc -i $file -o ${file%.*}.svg
             echo "${file%.*}.svg"
             git add ${file%.*}.svg
            done
      - name: push this svg files to pr-branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          commit_message: 'chore(docs): add static mermaid *.svg files"'
          file_pattern: '*.svg'
          repository: .
          # Optional commit user and author settings
          commit_user_name: GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
